spring.application.name=smartshelfx-backend

server.port=${PORT:8080}

spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/smartshelfxdata?createDatabaseIfNotExist=true}
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=${JWT_SECRET:GenerateASecretKeyForJWTs}
jwt.expiration=86400000

spring.jackson.serialization.fail-on-empty-beans=false

logging.level.com.smartshelfx=INFO
logging.level.org.springframework.web=WARN
logging.level.org.hibernate.SQL=WARN

ai.service.url=${AI_SERVICE_URL:http://localhost:8000}
cors.allowed.origins=${FRONTEND_URL:http://localhost:4200}
